# Generated by Django 4.2.7 on 2023-12-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
