# Generated by Django 4.2.7 on 2023-12-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
